NVIDIA-NeMo/RL

nemo_rl/algorithms/grpo.py, nemo_rl/data/llm_message_utils.py, nemo_rl/utils/logger.py
=> fix: logging validation samples was broken and not logging anything

.github/workflows/_run_test.yml
=> fix: Updated hf home cache dir back to the original one (after clean)

.github/workflows/cherry-pick-release-commit.yml, .github/workflows/semantic-pull-request.yml
Update cherry-pick workflow to pass semantic PR check.
This uses the change to the workflow templates here:
https://github.com/NVIDIA/NeMo-FW-CI-templates/pull/163
```python
```
* ...
=> ci: Update cherry-pick workflow to pass semantic PR check

docs/conf.py, docs/documentation.md, docs/project.json, docs/versions1.json
beep boop [🤖]: Hi @aschilling-nv 👋,
we've cherry picked #422 into  for you! 🚀
=> cp: `docs: Enable Version Switcher and Analytics Tracker (422)` into `r0.2.1`

.github/workflows/cicd-main.yml, codecov.yml, pyproject.toml
ci: Upload codecov
```python
```
* ...
=> ci: Upload codecov

nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/fsdp1_policy_worker.py
=> fix: only step scheduler during training

docs/debugging.md
=> docs: improve ray debugging instructions

nemo_rl/distributed/worker_groups.py, nemo_rl/models/generation/vllm.py, tests/unit/distributed/test_worker_groups.py
Previously in `update_weights`, we send all the handlers to vllm, that is for a 16node*8gpu running, we will send all 128 handles even if maybe only 8 of them is required by the current vllm worker.
This PR is to improve the refit time by only sending the required handlers.
The two 16node experiments manually set the timeout of `init_process_group` to 6000s and set dtype=bf16 in `AutoModelForCausalLM.from_pretrained`, otherwise it can't start. (https://github.com/NVIDIA/NeMo-RL/issues/443)
For 16node on ~30B models, both non MoE and MoE models have a big improvement on refit time.
| non-MoE: 18s -> 7s | MoE: 430s -> 50s |
|-|-|
| ![image](https://github.com/user-attachments/assets/ae012a86-0512-4ab3-a76f-969f7b96700d) | ![image](https://github.com/user-attachments/assets/e719ce3a-cade-4fb2 …
=> feat: refit speedup

nemo_rl/distributed/worker_groups.py
Remaking this PR due to accidental main shenanigans.
=> feat: Parallelized worker initialization

.github/workflows/build-test-publish-wheel.yml, .github/workflows/cherry-pick-release-commit.yml, .github/workflows/cicd-main.yml, .github/workflows/copyright-check.yml, .github/workflows/release-freeze.yml, .github/workflows/release.yaml, .github/workflows/semantic-pull-request.yml
ci: Fix GHA template ref after org move
```python
```
* ...
=> ci: Fix GHA template ref after org move

nemo_rl/experience/rollouts.py, tests/unit/distributed/test_virtual_cluster.py
=> fix: Fix incorrect merge to main

examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp1.v2.yaml, examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long.v2.yaml, examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp.v2.yaml, examples/configs/recipes/llm/sft-llama3.2-1b-1n8g-fsdp2tp1.v2.yaml, examples/configs/recipes/llm/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt.v2.yaml
=> fix: Add missing 'add_generation_prompt' key to SFT convergence tests

docs/model-quirks.md, nemo_rl/distributed/worker_groups.py, nemo_rl/experience/rollouts.py, nemo_rl/models/generation/vllm.py
=> feat: using v1 runtime for async rollouts

3rdparty/THIRD_PARTY_LICENSE_MATPLOTLIB, nemo_rl/algorithms/grpo.py, nemo_rl/utils/logger.py, pyproject.toml, tests/unit/utils/test_logger.py, uv.lock
Add logprob error visualization if above a threshold:
* wandb example: https://wandb.ai/nvidia/grpo-dev/runs/3p5e1w24/workspace?nw=nwuserzhiyul
* tensorboard example:
closes #318
```python
```
* ...
=> feat: token_mult_prob_error sample visualization if above a threshold

examples/configs/dpo.yaml, examples/configs/grpo_math_1B.yaml, examples/configs/grpo_sliding_puzzle.yaml, examples/configs/sft.yaml, nemo_rl/utils/logger.py, tests/functional/dpo.sh, tests/functional/grpo.sh, tests/functional/sft.sh, tests/test_suites/llm/sft-llama3.1-8b-instruct-1n8g-fsdp1.v2.sh, tests/test_suites/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long.v2.sh, tests/test_suites/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp.v2.sh, tests/test_suites/llm/sft-llama3.2-1b-1n8g-fsdp2tp1.v2.sh, tests/test_suites/llm/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt.v2.sh, tests/unit/utils/test_logger.py
* track system memory too in case there's a CPU OOM
* also switch everything to GB since it was slightly annoying having to convert from bytes to GB
=> feat: async ray monitoring now tracks system memory

.github/workflows/cicd-main.yml
=> fix: increase test timeout 2hr -> 3hr

nemo_rl/models/policy/dtensor_policy_worker.py
remove reference_model_buffers in fsdp2 to fix `DeepSeek-V2-Lite`'s following error.
```
RuntimeError: The size of tensor a (512) must match the size of tensor b (163840) at non-singleton dimension 0
```
| DeepSeek-V2-Lite | Llama-3.1-8B-Instruct |
|-|-|
| ![image](https://github.com/user-attachments/assets/3f1442db-7ece-4f8d-8977-748c1bc26d16) | ![image](https://github.com/user-attachments/assets/63bef9c2-562d-4d23-a53f-4e53ad5c8bd0) |
=> fix: remove reference_model_buffers in fsdp2

docs/model-quirks.md, docs/nsys-profiling.md
=> docs: fix some typos on nsys/model-quirk pages

nemo_rl/models/dtensor/parallelize.py
Closes #453 
```python
```
* ...
=> fix: update gemma3 prefix

examples/configs/dpo.yaml, examples/configs/grpo_math_1B_megatron.yaml, examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-megatron.yaml, examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-megatrontp2pp2-quick.yaml, examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-megatron.yaml, examples/configs/sft.yaml, nemo_rl/models/policy/megatron_policy_worker.py, tests/unit/models/generation/test_vllm_generation.py, tests/unit/models/policy/test_megatron_worker.py
=> enable mcore rope fusion

examples/configs/sft.yaml, nemo_rl/algorithms/dpo.py, nemo_rl/algorithms/grpo.py, nemo_rl/algorithms/sft.py, nemo_rl/utils/checkpoint.py, tests/unit/algorithms/test_sft.py
Closes #441 
```python
```
* ...
=> feat: decouple checkpointing from validation

nemo_rl/distributed/worker_groups.py, nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/lm_policy.py, nemo_rl/models/policy/megatron_policy_worker.py, nemo_rl/models/policy/utils.py, tests/unit/distributed/test_worker_groups.py, tests/unit/models/policy/test_utils.py
Allows policy-specific environment variables to be configured via `policy.env_vars`
```python
```
* ...
=> feat: plumb environment variables to RayWorkerGroup

README.md
**update converter path in README.**
N/A
* **doc update**
* ...
=> docs: update converter path in README.

pyproject.toml, uv.lock
=> fix: upgrade datasets to fix squad download

examples/configs/grpo_math_8B_megatron.yaml
=> fix: fix lr scheduler for config that was missed in #681

docs/design-docs/logger.md, examples/configs/dpo.yaml, examples/configs/grpo-deepscaler-1.5b-8K.yaml, examples/configs/grpo_math_1B.yaml, examples/configs/grpo_math_1B_megatron.yaml, examples/configs/grpo_sliding_puzzle.yaml, examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-fsdp2tp1.v2.yaml, examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-fsdp2tp2-quick.v2.yaml, examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-megatron.yaml, examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-megatrontp2pp2-quick.yaml, examples/configs/recipes/llm/dpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v2.yaml, examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml, examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml, examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml, examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt-long.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml, examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp1-long.v2.yaml, examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-fsdp2tp2sp.v2.yaml, examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-megatron.yaml, examples/configs/recipes/llm/sft-llama3.2-1b-1n8g-fsdp2tp1.v2.yaml, examples/configs/recipes/llm/sft-qwen2.5-32b-4n8g-fsdp2tp8sp-actckpt.v2.yaml, examples/configs/sft.yaml, examples/configs/sft_openmathinstruct2.yaml, nemo_rl/utils/logger.py, pyproject.toml, tests/unit/utils/test_logger.py, uv.lock
Copy of #534. Recreated to run CI + resolve conflicts
Closes #514
=> feat: MLFlow Integration for experiment tracking

README.md, docs/versions1.json, nemo_rl/package_info.py
=> chore: Bump 0.2.1 -> 0.3.0

examples/configs/sft.yaml
beep boop [🤖]: Hi @terrykong 👋,
we've cherry picked #717 into  for you! 🚀
=> cp: `fix: unset TP and PP in sft 1 GPU config (717)` into `r0.3.0`

examples/configs/grpo_math_8B.yaml
=> fix: remove dynamic batching from 8B llama dtensor config

nemo_rl/algorithms/dpo.py
beep boop [🤖]: Hi @ashors1 👋,
we've cherry picked #730 into  for you! 🚀
=> cp: `fix: guard DPO against dynamic batching and sequence packing (730)` into `r0.3.0`

docs/design-docs/training-backends.md
beep boop [🤖]: Hi @yfw 👋,
we've cherry picked #725 into  for you! 🚀
=> cp: `docs: Update docs to include submodule instructions (725)` into `r0.3.0`

examples/configs/grpo_math_qwen30ba3b_megatron.yaml
Disable sequence packing in qwen moe config to prevent hang
```python
```
* ...
=> fix: Disable sequence packing in qwen moe config to prevent hang

README.md, docs/design-docs/sequence-packing-and-dynamic-batching.md, docs/guides/grpo.md, docs/index.md, examples/configs/grpo_math_1B.yaml, examples/configs/grpo_math_1B_megatron.yaml
beep boop [🤖]: Hi @SahilJain314 👋,
we've cherry picked #729 into  for you! 🚀
=> cp: `docs: Added docs for sequence packing and dynamic batching (729)` into `r0.3.0`

README.md, docs/guides/eval.md
Update frontpage eval docs to match current implementation.
=> docs: fix frontpage outdated eval docs

README.md, docs/guides/eval.md
beep boop [🤖]: Hi @yuki-666 👋,
we've cherry picked #738 into  for you! 🚀
=> cp: `docs: fix frontpage outdated eval docs (738)` into `r0.3.0`

.github/workflows/community-bot.yml
=> ci: Fix community bot

nemo_rl/data/packing/algorithms.py, nemo_rl/distributed/batched_data_dict.py, tests/unit/data/packing/test_algorithms.py, tests/unit/distributed/test_batched_data_dict.py
beep boop [🤖]: Hi @SahilJain314 👋,
we've cherry picked #748 into  for you! 🚀
=> cp: `fix: Enforce minimum packed sequence bin count and multiple of bin count (748)` into `r0.3.1`

nemo_rl/models/policy/lm_policy.py
=> fix: Removed assertion for dtensor | megatron now that FSDP1 is gone

nemo_rl/distributed/model_utils.py, tests/unit/distributed/test_model_utils.py
beep boop [🤖]: Hi @SahilJain314 👋,
we've cherry picked #761 into  for you! 🚀
=> cp: `feat: avoid softmax deepcopy in logprobs (tpoisonooo) (761)` into `r0.3.1`

CONTRIBUTING.md
=> docs: update contributing docs to have an external section

README.md
=> docs: v0.3 blog post

nemo_rl/environments/code_environment.py
**Fix the return type of execute() inside code_environment.**
List issues that this PR closes ([syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)): N/A
N/A
* ...
=> fix: fix the return type of `execute()`.

docs/design-docs/design-and-philosophy.md
=> docs: add a section on our config design

docs/versions1.json, nemo_rl/package_info.py
=> chore: 0.3.0 -> 0.3.1

pyproject.toml, uv.lock
- Upgrade pillow version to 11.3.0, fix for CVE
* ...
=> chore: update pillow to 11.3.0 - cve

README.md
This completion for [#807](https://github.com/NVIDIA-NeMo/RL/pull/807). Update readme checkpoint conversion guide section
* @ashors1/@terrykong could review and anyone in the community.
=> docs: fix checkpointing command for megatron->hf export 

examples/run_vlm_grpo.py, nemo_rl/data/llm_message_utils.py, nemo_rl/data/multimodal_utils.py, nemo_rl/distributed/batched_data_dict.py, tests/unit/data/test_multimodal_dict.py
=> Remove multimodal batch/item distinction 2

.github/workflows/_automodel_integration_check.yml, nemo_rl/models/dtensor/parallelize.py
Update Automodel integration check logic and message.
* ...
=> fix: Update Automodel integration check logic and message.

nemo_rl/models/megatron/community_import.py, nemo_rl/models/policy/megatron_policy_worker.py
=> feat: Gpu import with Megatron-Bridge

.gitmodules
- https://github.com/NVIDIA/NeMo.git is now https://github.com/NVIDIA-NeMo/NeMo.git, updating the submodules
- PR in main - https://github.com/NVIDIA-NeMo/RL/pull/1016
```python
```
* ...
=> chore: update NeMo git URL in submodules

nemo_rl/models/policy/megatron_policy_worker.py
=> fix: [mcore] only take optimizer steps when in train mode

examples/configs/grpo_math_1B.yaml, examples/configs/grpo_math_1B_megatron.yaml, examples/configs/grpo_sliding_puzzle.yaml, examples/configs/recipes/llm/grpo-deepscaler-1.5b-8K.yaml, examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml, examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml, examples/configs/recipes/llm/grpo-gspo-deepscaler-1.5b-8K.yaml, examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-1n8g-megatron-fp8.yaml, examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-2n8g-fsdp2tp1-noncolocated.yaml, examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml, examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml, examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-megatron.yaml, examples/configs/recipes/llm/grpo-math-qwen3-30ba3b-megatron-tp4-32k.yaml, examples/configs/recipes/llm/grpo-moonlight-16ba3b-4n8g-megatron.yaml, examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt-long.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-megatron.yaml, examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml, examples/configs/recipes/vlm/vlm_grpo-qwen2.5-vl-3b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml, examples/configs/recipes/vlm/vlm_grpo-smolvlm2-2.2b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml, examples/configs/vlm_grpo_3B.yaml, nemo_rl/algorithms/grpo.py
The PR adds multi-epoch support to GRPO
Closes https://github.com/NVIDIA-NeMo/RL/issues/711
=> feat: Support Multi-epoch training in GRPO
