examples/configs/grpo_math_8B.yaml
Make dtensor default in 8b config; fixes broken example in README fo multinode
README example for multinode was broken:
```    
assert config["dtensor_cfg"]["enabled"], (           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
AssertionError: Dynamic batch is only supported for DTensor policy.
```
```python
```
* ...
=> fix: Make dtensor default in 8b config

nemo_rl/distributed/virtual_cluster.py
This is okay to do for all local clusters b/c ray's default behavior is to find another port if the current one is taken. It's up to the user to look up the port in the logs to see which port to attach the debugger to (or to open the dashboard)
@gshennvm
=> fix: enable dashboard on local clusters

.github/workflows/cherry-pick-release-commit.yml, .github/workflows/semantic-pull-request.yml
cp: `ci: Update cherry-pick workflow to pass semantic PR check (#414)` into `r0.2.1`
This aims to resolve the semantic PR failure on the release branch.
```python
```
* ...
=> cp: `ci: Update cherry-pick workflow to pass semantic PR check (#414)` into `r0.2.1`

.gitignore, docker/README.md
People aren't necessarily seeing the docker documentation page in our documentation, so I added a small README to the docker/ dir to point to it. Also, .gitignore was ignoring the Dockerfile, so I fixed that as well.
=> docs: Added a small pointer doc to the docker dir to prevent confusion

.github/workflows/cicd-main.yml
Set codecov override_branch to main if from merge queue. 
The codecov upload works, but when it's ran during a merge queue, it uses the temporary branch as the name.  We should just set this to 'main'.
```python
```
* ...
=> ci: Set codecov override_branch to main if from merge queue

docs/cluster.md, ray.sub
=> feat: parametrize GPUS_PER_NODE and CPUS_PER_WORKER in ray.sub

.github/workflows/release.yaml
Update release workflow to optionally release pypi without github release.
Afer this merges, we will attempt to push the package for the existing release 0.2.1.
```python
```
* ...
=> ci: Update release workflow to optionally release pypi without github release

nemo_rl/environments/math_environment.py, tests/unit/environments/test_math_environment.py
closes #451 
So I think I've root caused the issue. It's basically that math-verify can throw a class TimeoutException(BaseException), but math-verify doesn't catch this exception. Since BaseException is reserved for things like keyboard interrupt, it can crash the ray actor. Simply catching this should resolve this.
=> fix: math-verify intermittent failure due to timeout

nemo_rl/models/dtensor/parallelize.py
Hi from pytorch fsdp2! set `fully_shard(reshard_after_forward=False)` to keep the memory behavior the same after pytorch side change: https://github.com/pytorch/pytorch/pull/154704
for root model, `reshard_after_forward=False` means keep root parameters unsharded after forward, since they will be used in the backward immeidately. This is a AA change
```python
uv run python examples/run_grpo_math.py cluster.gpus_per_node=8
```
* ...
=> fix: [FSDP2] reshard_after_forward=False for root model

examples/configs/grpo-deepscaler-1.5b-8K.yaml, examples/configs/grpo_math_1B.yaml, examples/configs/grpo_math_8B.yaml, examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml, examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml, examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml, examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt-long.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp1.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml, nemo_rl/algorithms/grpo.py, nemo_rl/models/policy/__init__.py, nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/fsdp1_policy_worker.py, nemo_rl/models/policy/hf_policy.py, nemo_rl/models/policy/interfaces.py, nemo_rl/utils/nvml.py, tests/unit/models/generation/test_vllm_generation.py
Compute `refit_buffer_size_gb` by remaining memory at refitting process instead of manually set it.
I kept `refit_buffer_size_gb` param at `refit_policy_generation()` and `prepare_weights_for_ipc()` only for unit test, and removed it at any other places.
Closes https://github.com/NVIDIA/nemo-rl/issues/249
```python
```
* ...
=> feat: remove manual refit param

ray.sub
4 node run looks to have no effect by allowing head node to be scheduleable
=> feat: head node in ray.sub becomes schedulable to simplify deployment

nemo_rl/experience/rollouts.py, nemo_rl/models/generation/vllm.py
1. Allow rollouts to use async generate.
2. Fix async generate sampling params to allow only the required number of tokens to be generated.
```python
```
* ...
=> fix: async rollouts; incorrect tokens generated

.github/workflows/_run_test.yml, .github/workflows/cicd-main.yml, README.md, docker/Dockerfile, nemo_rl/distributed/virtual_cluster.py, pyproject.toml, uv.lock
Bump
* torch 2.60 -> 2.70
* transformer-engine 1.13 -> 2.3
* ray 2.43 -> 2.46
* vllm 0.8.5 -> 0.9
Also changes our base image to a more performant image
LLama8b perf:
* green = status quo
* yellow = old anyscale container (also on torch 2.6)
* gray = new base container (also on torch 2.6)
* brown = new base container (on **torch 2.7**)
Created an issue to track the investigation and documentation of this cuda base version skew https://github.com/NVIDIA/NeMo-RL/issues/486
For posterity, I am able to run this locally on my workstation with these drivers:
```
| NVIDIA-SMI 575.57.08              Driver Version: 575.57.08      CUDA Version: 12.9     |
```
Closes #468
=> fix(chore): bump vllm, TE, ray, torch + more performant cuda base

docs/adding-new-models.md, nemo_rl/experience/rollouts.py, nemo_rl/models/generation/vllm.py, tools/model_diagnostics/1.max_model_len_respected.py
Example failure:
```
uv run --extra vllm tools/model_diagnostics/1.max_model_len_respected.py
...
Processed prompts: 100%|███████████| 1/1 [00:00<00:00,  2.15it/s, est. speed input: 19.34 toks/s, output: 25.79 toks/s]
Prompt tokens: 9
Generated tokens: 12
Total tokens: 21
[rank0]: Traceback (most recent call last):
[rank0]:   File "/lustre/fsw/portfolios/coreai/users/terryk/rewrite-aligner/reinforcer/tools/model_diagnostics/1.max_model_len_respected.py", line 34, in <module>
[rank0]:     assert num_total_tokens <= llm.llm_engine.model_config.max_model_len, f"num_total_tokens={num_total_tokens} > max_model_len={llm.llm_engine.model_config.max_model_len} for model={args.model}, which should not happen."
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> fix: add more checks for seq len as well as a script to check `max_model_len`

.github/workflows/cicd-main.yml, examples/configs/grpo-deepscaler-1.5b-8K.yaml, examples/configs/grpo_math_1B.yaml, examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml, examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml, examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml, examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt-long.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-32b-16n8g-fsdp2tp8sp-actckpt.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp1.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml, nemo_rl/algorithms/grpo.py, nemo_rl/distributed/ray_actor_environment_registry.py, nemo_rl/models/generation/interfaces.py, nemo_rl/models/generation/vllm.py, nemo_rl/models/generation/vllm_backend.py, nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/hf_policy.py, nemo_rl/models/policy/interfaces.py, tests/functional/grpo_non_colocated.sh, tests/unit/experience/test_rollouts.py, tests/unit/models/generation/test_vllm_generation.py, tests/unit/models/generation/test_vllm_large_model.py, tests/unit/utils/test_native_checkpoint.py
Support non-colocated sync vllm.
pink: colocated baseline, using 4 node.
green/blue: non-colocated, using 4 node for train and 1 node for inference.
Train resources will be inferred from overall and inference resources.
i.e. training nodes = overall nodes - inference nodes
```python
uv run python examples/run_grpo_math.py \
policy.generation.colocated.enabled=false \
policy.generation.colocated.resources.gpus_per_node=4
uv run python examples/run_grpo_math.py \
policy.generation.colocated.enabled=false \
policy.generation.colocated.resources.num_nodes=1
```
* ...
=> feat: support non-colocated sync vllm

docs/cluster.md, docs/debugging.md, docs/index.md, docs/nsys-profiling.md, nemo_rl/__init__.py, nemo_rl/algorithms/dpo.py, nemo_rl/algorithms/grpo.py, nemo_rl/algorithms/sft.py, nemo_rl/distributed/worker_group_utils.py, nemo_rl/distributed/worker_groups.py, nemo_rl/models/generation/vllm.py, nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/fsdp1_policy_worker.py, nemo_rl/models/policy/lm_policy.py, nemo_rl/models/policy/megatron_policy_worker.py, nemo_rl/utils/nsys.py, pyproject.toml, ray.sub, tests/unit/distributed/test_worker_groups.py, tests/unit/distributed/test_worker_groups_utils.py, tests/unit/models/generation/test_vllm_generation.py, tests/unit/test_nsight_patching.py, tests/unit/utils/test_nsys.py, uv.lock
Closes #216 
Potentially solves #383 
To allow nsys profiling had to fix how the default options were propagated from `@ray.remote(...)` get propagated in the `RayWorkerGroup`.
Also there's a bug in upstream ray for nsight + py_executable that I'll submit a fix for, but in order to use nsys today, this PR includes patches in `__init__.py` and `ray.sub`.
=> feat: add nsys profiling for for dtensor and vllm workers 

nemo_rl/distributed/worker_groups.py
Small fix to not use types from the private `ray._raylet` package and instead use them from the public `ray` package.
I also made fix upstream in Ray so the repr of the type show the correct `ray.ObjectRef` instead of the private version `ray._raylet.ObjectRef` (https://github.com/ray-project/ray/pull/54011)
=> fix: fix Ray typing to not use internal package

examples/configs/sft_openmathinstruct2.yaml
=> fix: add dynamic_batching key to SFT OpenMathInstruct config

nemo_rl/models/policy/megatron_policy_worker.py
This is to address a bug found when testing Nemotron-H where the params_dtype gets set incorrectly and add an assert to give a hint of what might have happened if activation_func is empty.
The issue was during conversion we use the [default value](https://github.com/NVIDIA/Megatron-LM/blob/1ab876ddc4c1893c76f26d775226a8d1dcdfb3d2/megatron/core/optimizer/optimizer_config.py#L56) of the optimizer.params_dtype as float32 here https://github.com/NVIDIA/NeMo/blob/bab66472d2f2eb05ab621dbad66ad6031e4ee19e/nemo/tron/converter/common.py#L217. But the params_dtype is supposed to be set by the `bf16` and `fp16` args according to how it's handled in mcore: https://github.com/NVIDIA/Megatron-LM/blob/1ab876ddc4c1893c76f26d775226a8d1dcdfb3d2/megatron/training/arguments.py#L676
This change just respects …
=> fix: correct mcore dtype + assertion on activation_func

examples/configs/dpo.yaml, examples/configs/grpo_math_1B_megatron.yaml, examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-megatron.yaml, examples/configs/recipes/llm/dpo-llama3.1-8b-instruct-4n8g-megatrontp2pp2-quick.yaml, examples/configs/recipes/llm/sft-llama3.1-8b-instruct-1n8g-megatron.yaml, examples/configs/sft.yaml, nemo_rl/models/policy/megatron_policy_worker.py
When using overlap param gather, Mcore does a single param all-gather after each backward pass (before the first forward step). This is problematic when the first forward pass following a backward pass is using the reference model parameters, because we end up doing an all-gather on the reference parameters rather than the model being trained. The solution is to disable overlap param gather when running reference model forward and re-enable after.
Closes #552 
```python
```
* ...
=> fix: fix overlap param gather

docs/guides/grpo-deepscaler.md
**This PR attempts to fix the document for deepscaler experiments**
Currently, necessary arguments are missing, which leads to poor evaluation results
```
============================================================
model_name='step_300-hf' dataset_name='aime_2024'
max_new_tokens=2048 temperature=0.0 top_p=1.0 top_k=-1
metric='pass@1' num_tests_per_prompt=1
score=0.0333 (1.0/30)
============================================================
```
By specifying `cot.txt` (as is done in training setup), the result improves a bit.
```
============================================================
model_name='step_300-hf' dataset_name='aime_2024'
max_new_tokens=2048 temperature=0.0 top_p=1.0 top_k=-1
metric='pass@1' num_tests_per_prompt=1
score=0.1333 (4.0/30) …
```
=> docs: Add missing arguments to DeepScaler evaluation

nemo_rl/algorithms/grpo.py
add 
`drop_last=True `
to prevent divisible error by dropping last batch in loader
```python
```
* ...
=> fix: prevent divisible error by dropping last batch in loader

nemo_rl/distributed/worker_groups.py, nemo_rl/models/generation/vllm.py, nemo_rl/models/policy/lm_policy.py, tests/unit/distributed/test_worker_groups.py
Under some conditions, ray stops respecting non-kwargs arguments.
This PR supports passing args/kwargs in`run_all_workers_multiple_data` and `run_all_workers_sharded_data`, so that we can pass through kwargs instead of passing an unclear param `data`.
=> feat: improve worker group args/kwargs

examples/run_sft.py, nemo_rl/data/hf_datasets/__init__.py, nemo_rl/data/hf_datasets/oai_format_dataset.py, tests/unit/data/hf_datasets/test_oai_format_dataset.py
This PR enables using the OpenAI format dataset from a `json/jsonl` when running SFT.
Modify `examples/configs/sft.yaml`
```yaml
data:
max_input_seq_length: ${policy.max_total_sequence_length}
dataset_name: "openai_format"
add_bos: true
add_eos: true
add_generation_prompt: false
train_data_path: "datasets/train.json"
val_data_path: "datasets/valid.json"
chat_key: "messages"  # set chat_key like "messages" and "conversations"
system_key: null  # (optional) set system_key (system_prompt key name) if dataset has
system_prompt: null  # (optional) set system_prompt, e.g., "You are a …
```
=> feat: add OpenAI format dataset for SFT

nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/megatron_policy_worker.py, nemo_rl/models/policy/utils.py
=> fix: enable expandable segments for hopper+

nemo_rl/algorithms/loss_functions.py, nemo_rl/distributed/model_utils.py, nemo_rl/models/dtensor/parallelize.py, nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/megatron_policy_worker.py
This PR optimize get logprobs when CP is enabled for FSDP2. Issue #549 
In previous PR, the logits were retrieved from sharded one (local tensor shape [b, s / cp_size, v / tp_size]) into full tensor with shape [b, s, v] and passed to loss function.
The key reason was we had to ensure sequence order was correct when get log probs.
This PR allows permuted sequenced to pass to loss function with additional full tensor `seq_index` which indicates the order of the permuted sequence and allow parallel logprobs computation even mixed with tp enabled. 
**cp8**
| convergence | time cost |
|-|-|
| ![image](https://github.com/user-attachments/assets/0ecc8887-60ab-4ecc-bb4c-25f4fc5ed09a) | ![image](https://github.com/user-attachments/assets/0bf3053c-90e7-4778-b275-8efd8df4a7b3) |
**tp4cp2**
| …
=> feat: optimize get logprobs when cp enabled.

tests/unit/conftest.py
Fixes bug when running  pytest_sessionfinish hook in case there is no _unit_test_data 
`uv run --group test pytest --collect-only`
* ...
=> fix: pytest_sessionfinish hook in case there is no _unit_test_data.

README.md, nemo_rl/models/policy/dtensor_policy_worker.py
(enabling sp converts internal buffers to dtensor and broadcast was failing)
Fixes below issue seen with some models:
```
(DTensorPolicyWorker pid=343603)   File "/app/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/distributed/tensor/_dispatch.py", line 393, in unwrap_to_op_info [repeated 6x across cluster]
(DTensorPolicyWorker pid=343603)     assert compute_mesh is not None, ( [repeated 6x across cluster]
(DTensorPolicyWorker pid=343603)            ^^^^^^^^^^^^^^^^^^^^^^^^ [repeated 6x across cluster]
(DTensorPolicyWorker pid=343603) AssertionError: found no DeviceMesh from dtensor args for c10d.broadcast_.default! [repeated 6x across cluster]
```
Closes https://github.com/NVIDIA-NeMo/RL/issues/621.
* **You can potentially add …
=> fix: Don't call broadcast on dtensor 

.github/workflows/cicd-main.yml, nemo_rl/distributed/virtual_cluster.py, nemo_rl/environments/games/sliding_puzzle.py, nemo_rl/environments/math_environment.py, nemo_rl/models/generation/vllm.py, nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/megatron_policy_worker.py, nemo_rl/utils/venvs.py, pyproject.toml
Change excludes ray.remotes from coverage. Brings coverage from 45 -> 58% (still a large gap)
also print the missing lines
=> chore: exclude ray.remote from coverage

.gitignore, docs/guides/use-custom-vllm.md, docs/index.md, tools/build-custom-vllm.sh
Some models require testing a fix from vllm that's not in a released branch. This change adds a script that builds vllm as well as a guide that shows how to configure NeMo RL to use it
=> feat: guide to configure custom vllm version

nemo_rl/models/generation/vllm.py, nemo_rl/models/generation/vllm_backend.py, nemo_rl/models/policy/dtensor_policy_worker.py
Adds explicit `NCCL_CUMEM_ENABLE=1` environment variable setting to resolve P2P initialization failures in distributed training with vLLM.
Please see detailed analysis in https://github.com/NVIDIA-NeMo/RL/issues/564#issuecomment-3050323063.
Closes #564.
This PR can also be helpful to #613. Maybe @yuki-666 could take a look. The only change you may need to make it to delete the `os.environ["NCCL_CUMEM_ENABLE"] = "0"` in function `init_collective` for `nemo_rl/models/policy/megatron_policy_worker.py`.
I have tested the settings @yuki-666 provided: 8b model grpo on 5 nodes:
Where
- Purple line: `exp1_5n_non_colocated_p2p_disabled`: before the fix, running with `NCCL_P2P_DISABLE=1`.
- Pink line: `exp2_5n_non_colocated_fix`: after this pr's fix.
We can see that:
- The training reward mostly …
=> fix: fix nccl P2P initialization error for non-colocated

nemo_rl/models/generation/vllm.py, nemo_rl/models/generation/vllm_backend.py
Optimization for refitting:
* avoid duplicate ipc passing across ray: it removes one linearity factor in TP scaling in refitting. Instead of broadcast all ipc handles just sent the necessary ones. The overhead in argument serialization is constant to TP scaling now. 
- see ~25% gain in refitting speed in small scale and expect to be much more impactful with with large TP size.
- in dsv3 w/ 64 tp. Found 3.5x speed (from 420s to 120s) with the change.
* ~avoid waiting for update_weights_from_ipc_handles for better overlap:~
-  ~avoid unnecessary waiting time for better overlap \~8% gain in refitting speed in small scale~
- reverted given unsafe memory control 
List issues that this PR closes ([syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pul …
=> feat: optimize refit by reducing set of IPC handles sent to each device

docs/design-docs/training-backends.md, nemo_rl/models/policy/megatron_policy_worker.py, nemo_rl/models/policy/utils.py, tests/unit/models/policy/test_utils.py
when running multinode, unless someone knows to mount `/opt/checkpoints` everywhere, their multinode will fail. This change introduces the following dir precedence
```
1. **`NRL_MEGATRON_CHECKPOINT_DIR`** - Custom checkpoint directory path
2. [RECOMMENDED] **`HF_HOME/nemo_rl`** - Uses HuggingFace cache directory if available
3. **`~/.cache/huggingface/nemo_rl`** - Default fallback location
```
Most will specify HF_HOME, so this will seemlessly work with those training large models on multiple nodes.
Also, default to the cache dir otherwise since `/opt` is usually reserved for "optional packages" as opposed to data mounts (which usually reside in `/mnt`)
=> feat: introduce megatron checkpoint dir precedence

examples/configs/grpo_math_1B_megatron.yaml, examples/configs/grpo_math_70B_megatron.yaml, examples/configs/grpo_math_qwen30ba3b_megatron.yaml, nemo_rl/models/policy/megatron_policy_worker.py, tests/unit/models/policy/test_megatron_worker.py
=> fix: make mcore lr scheduler configuration consistent with dtensor

examples/configs/grpo_math_70B_megatron.yaml, examples/configs/grpo_math_8B_megatron.yaml, examples/configs/grpo_math_qwen30ba3b_megatron.yaml
- decreases `gpu_memory_utilization` for Llama 8B and 70B configs to avoid OOM
- updates Qwen3 30B-A3B parallelism for a 30% speedup in step time
```python
```
* ...
=> fix: Megatron config updates to avoid OOM

docs/model-quirks.md, nemo_rl/distributed/batched_data_dict.py, nemo_rl/distributed/model_utils.py, nemo_rl/models/dtensor/parallelize.py, nemo_rl/models/huggingface/common.py, nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/lm_policy.py
Enable CP for dtensor during get_logprobs. Such we could align with mcore path.
```python
```
=> feat: Enable CP during get_logprobs for dtensor worker.

docs/model-quirks.md, nemo_rl/models/policy/dtensor_policy_worker.py, tests/unit/models/policy/test_dtensor_worker.py
Add an assertion to avoid using CP+SP (sequence parallel) in DTensor worker.
Related issue: https://github.com/NVIDIA-NeMo/RL/issues/659.
=> chore: add CP+SP (sequence parallel) assertion in DTensor worker

nemo_rl/models/policy/megatron_policy_worker.py
After dtype issue fixed:
1. `refit_param_info_mcore` can be cached and no need to call `get_param_info` each time in `prepare_weights_for_ipc`. This won't offer any speed optimization (or maybe too small to see).
2. `refit_param_info_hf` is no need to cache anymore, we used it to compare dtype before and now it's fixed.
=> feat: cache refit_param_info_mcore

examples/configs/grpo_math_8B.yaml
cherry-pick workflow missed this one since it didn't have `r0.3.0` label when it landed in main
=> cp: `fix: remove dynamic batching from 8B llama dtensor config (#728)`

nemo_rl/models/generation/vllm.py, nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/utils.py
=> fix: Use the conditional temperature scaling in get_logprobs as well

nemo_rl/data/packing/algorithms.py, nemo_rl/distributed/batched_data_dict.py, tests/unit/data/packing/test_algorithms.py, tests/unit/distributed/test_batched_data_dict.py
Fixes bin counts being too low with GBS is low as reported by @ZhiyuLi-Nvidia and also #718.
=> fix: Enforce minimum packed sequence bin count and multiple of bin count

nemo_rl/distributed/model_utils.py, tests/unit/distributed/test_model_utils.py
Clone of #683 with added tests.
=> feat: avoid softmax deepcopy in logprobs (tpoisonooo)

docs/guides/eval.md, nemo_rl/data/eval_datasets/__init__.py, nemo_rl/data/eval_datasets/aime2025.py, pyrefly.toml
**Add AIME-2025 eval dataset.**
List issues that this PR closes ([syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)): N/A
* **Run evaluation on AIME-2025**
```python
uv run examples/run_eval.py --config examples/configs/evals/aime2025.yaml cluster.gpus_per_node=8
```
* ...
=> feat: add AIME-2025 eval dataset.

docs/design-docs/env-vars.md, docs/index.md, tests/unit/distributed/test_worker_groups.py
closes #654 
```python
```
* ...
=> docs: documentation and unit test for env var precedence

nemo_rl/algorithms/grpo.py
As attached. Add the following metrics:
* train/mean_prompt_length: mean token length of prompt
* train/total_num_tokens: total num of tokens (including prompt and generation tokens)
* train/throughput_per_gpu: num of tokens per second (including prompt and generation tokens)
https://wandb.ai/nvidia/grpo-dev/runs/33pb40kk?nw=nwuserzhiyul
As a quick verification/test:
* train/total_num_tokens =  num_prompts_per_step x num_generations_per_prompt x (train/mean_prompt_length + train/mean_total_tokens_per_sample)
- actual: 2869598 vs calculated 2869596.16 (numerical difference)
*  train/throughput = train/total_num_tokens / step time / total_num_gpus
- actual: 1199 vs  1199
List issues that this PR closes …
=> feat: add throughput/prompt_length/total_num_tokens metrics

examples/run_grpo_math.py, nemo_rl/data/datasets.py, tests/unit/data/test_data_processor.py
=> fix: avoid duplicate bos by adding add_special_tokens=False

docs/guides/eval.md, examples/configs/evals/eval.yaml, nemo_rl/environments/code_environment.py, nemo_rl/environments/games/sliding_puzzle.py, nemo_rl/environments/interfaces.py, nemo_rl/environments/math_environment.py, nemo_rl/environments/tools/retriever.py, nemo_rl/evals/eval.py, nemo_rl/experience/rollouts.py, tests/unit/algorithms/test_grpo.py, tests/unit/evals/test_eval.py, tests/unit/test_envs.py
Add support for cons@k metric in evaluation module to improve performance measurement.
To be more specific:
1. Add extracted_answer to EnvironmentReturn.metadata.
2. Implement the function of selecting the majority of answers among k_value answers.
3. Enumerate all combinations in C(k, n) and calculate the corresponding scores, and finally get an unbiased estimate of cons@k.
Closes #541 
When k_value is set to 1, the values of pass@k and cons@k should be equal. By adding some print statements and running the following command:
```bash
uv run python examples/run_eval.py eval.metric="cons@k"
```
the results are as follows:
```
pass@k: 0.1(3.0/30)
cons@k: 0.1(3.0/30)
============================================================
model_name='Qwen2.5-Math-1.5B-Instruct' dataset_name='aime2024' …
```
=> feat: implement cons@k evaluation

examples/converters/convert_dcp_to_hf.py, examples/run_dpo.py, nemo_rl/data/llm_message_utils.py
- Convert the model weights from PyTorch’s .bin to safetensors as it is more secure and an ask from security.
- Get the path to `config.jsonl` from checkpoint dir
- Enable tool calling in alignment datasets
* ...
=> chore: enable tool calling and output safetensors in distributed checkpoint

examples/run_dpo.py, nemo_rl/algorithms/dpo.py
- Fixes the response Tuple returned during setup and initialization in `dpo.py`
- Remove `log_hyperparams` because it logs information before the backend is ready / initialized which causes crashes
* ...
=> fix: fix Tuple response + move log_hyperparam responsibility to caller

docs/model-quirks.md, examples/configs/grpo-deepscaler-1.5b-24K.yaml, examples/configs/grpo-deepscaler-1.5b-8K.yaml
=> fix: force use of eager (disabled cuda graphs) due to convergence issues

nemo_rl/algorithms/loss_functions.py
Enables CP with DTensor for DPO and SFT
DPO loss: 
SFT loss:
```python
```
* ...
=> feat: support DTensor CP in DPO and SFT

nemo_rl/models/generation/vllm.py, nemo_rl/models/generation/vllm_backend.py, nemo_rl/models/policy/megatron_policy_worker.py, pyproject.toml, tests/unit/models/generation/test_vllm_generation.py, uv.lock
Support non-colocated (both sync and async) in mcore worker.
`logprob_inference_prep` is slower than colocated is because we need to offload optimizer here, colocated already offload it in `refit_policy_generation`.
1. llama3
colocated (baseline): using 2 node.
non-colocated: using 2 node for train and 1 node for inference.
| Convergence | Time Cost |
|-|-|
| <img width="1812" height="632" alt="image" src="https://github.com/user-attachments/assets/9bf54c33-b0b5-4303-8879-14edf8fff449" /> | <img width="1834" height="1250" alt="image" src="https://github.com/user-attachments/assets/6c8662e0-0e1d-47f9-a09d-84fc53375489" /> |
2. dsv3
colocated (baseline): using 32 node.
non-colocated: using 32 node for train and 8/16 node for inference.
| Convergence | Time Cost |
|-|-|
| <img width="1778" …
=> feat: support non-colocated in mcore

nemo_rl/models/policy/dtensor_policy_worker.py, tests/unit/models/generation/test_vllm_generation.py
This PR fix the error below.
FSDP2's CPUOffloadPolicy needs model on CPU before forward and will auto offload model to CPU after backward, so we need to manually onload model before refit and offload model after refit.
<details>
<summary>Error Log</summary>
```
File "xxx/nemo_rl/models/policy/dtensor_policy_worker.py", line 1286, in broadcast_weights_for_collective
tensor = tensor.full_tensor()
^^^^^^^^^^^^^^^^^^^^
File "/opt/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/distributed/tensor/_api.py", line 570, in full_tensor
redist_res = self.redistribute(
^^^^^^^^^^^^^^^^^^
File "/opt/ray_venvs/nemo_rl.models.policy.dtensor_policy_worker.DTensorPolicyWorker/lib/python3.12/site-packages/torch/distributed/tensor/_api.py", line …
```
=> fix: fix non-colocated with cpu_offload enabled

.pre-commit-config.yaml, README.md, docs/conf.py
- Link uv's installation instructions to uv's website.
- Add a parsing callback in `docs/conf.py` to convert GitHub alerts in Markdowns into RST properly. ([since myst-parser doesn't seem to support it](https://github.com/executablebooks/MyST-Parser/issues/845#issue-2045915631)).
- Replace pyrefly's pre-commit hook from a `repo` hook to a `local` hook that runs pyrefly via `uv`'s `dev` environment.
- There are situations where `pip install uv` is not suitable. For example, for conda users who have a default `base` conda environment, `pip install uv` would only install uv into the `base` environment; in this case, using the standalone installer would be more suitable. Therefore, this PR replaces `pip install uv` with a link to the installation instructions from uv's website.
- [Myst-parser …
=> docs: Link uv's installation instructions to uv's website

.gitmodules, nemo_rl/models/megatron/community_import.py
=> feat: qwen3 export to HF

docs/model-quirks.md, examples/configs/grpo_math_1B.yaml, examples/configs/recipes/llm/grpo-deepscaler-1.5b-8K.yaml, nemo_rl/models/dtensor/parallelize.py, nemo_rl/models/huggingface/common.py, nemo_rl/models/policy/dtensor_policy_worker.py, tests/unit/models/generation/test_vllm_generation.py, tests/unit/models/generation/test_vllm_large_model.py, tests/unit/models/huggingface/test_common.py, tests/unit/models/policy/test_dtensor_worker.py, tests/unit/models/policy/test_megatron_worker.py, tests/unit/utils/test_native_checkpoint.py
This pull request removes the tie weight check in the DTensor Worker, addressing a previous limitation with training models that utilize tie_word_embeddings when tensor parallel size (tp_size) > 1.
closes #684 
Experiments were run with meta-llama/Llama-3.2-1B, Qwen/Qwen2.5-1.5B-Instruct and google/gemma-2-2b-it. With the truncate rate set within a reasonable range, both tp_size=1 and tp_size=2 produced comparable reward results, indicating that training proceeds as expected. This demonstrates consistency in model behavior across different tensor parallel configurations, confirming correct handling of tied word embeddings during training.
Main setup:
- policy.generation.temperature=1.0
- policy.max_total_sequence_length=2048 
- cluster.gpus_per_node=8
<p align="center">
</p>
<p …
=> fix: remove tie weight check

docs/testing.md, nemo_rl/distributed/virtual_cluster.py, nemo_rl/models/dtensor/parallelize.py, nemo_rl/models/policy/dtensor_policy_worker.py, pyproject.toml, tests/unit/L0_Unit_Tests_Generation.sh, tests/unit/L0_Unit_Tests_Other.sh, tests/unit/L0_Unit_Tests_Policy.sh, tests/unit/conftest.py, tests/unit/models/policy/test_dtensor_worker.py, tests/unit/prepare_unit_test_assets.py, uv.lock
adds nm5 sharding, it supports 32K context in my small script testing.
No need to shard mamba layers, act ckpt is enough. shards only the mlps
=> feat: add nemotron5 sharding

nemo_rl/models/dtensor/parallelize.py
This PR enables tensor parallelism (TP) for Gemma3 models by adding support for parallelizing the embed_tokens and lm_head layers. Previously, these layers were excluded from TP due to tied word embeddings constraints, but with the removal of TP plan restrictions, Gemma3 models can now fully leverage tensor parallelism.
- Modified _parallelize_gemma3() function in nemo_rl/models/dtensor/parallelize.py:
- Added embed_tokens to tensor parallel plan using ColwiseParallel()
- Added lm_head to tensor parallel plan using RowwiseParallel()
- Updated sequence parallel plan to include proper configurations for both layers
- Removed the previous workaround using PrepareModuleOutput and PrepareModuleInput
List issues that this PR closes : #812 
Command:
```bash
NRL_FORCE_REBUILD_VENVS=true uv run …
```
=> feat: Add TP to embed_tokens and lm_head for Gemma models

nemo_rl/data/llm_message_utils.py, tests/unit/data/test_llm_message_utils.py
Currently the data processing will strip the final newline after an eos token which may nudge training to not produce a newline after eos token. The tokenizer that this could be an issue for is qwen which always append a newline after eos_token.
closes #932 
```python
```
* ...
=> fix: do not remove newlines after final eos_token in data processing

.github/workflows/_automodel_integration_check.yml, .github/workflows/_submodule_check.yml, .github/workflows/cicd-main.yml, .gitmodules, examples/configs/grpo_math_1B.yaml, nemo_rl/algorithms/loss_functions.py, nemo_rl/distributed/model_utils.py, nemo_rl/distributed/ray_actor_environment_registry.py, nemo_rl/distributed/virtual_cluster.py, nemo_rl/models/dtensor/parallelize.py, nemo_rl/models/policy/__init__.py, nemo_rl/models/policy/dtensor_policy_worker_v2.py, nemo_rl/models/policy/lm_policy.py, pyproject.toml, tests/unit/models/policy/test_dtensor_worker.py, tests/unit/models/policy/test_dtensor_worker_v2.py, tests/unit/models/policy/test_megatron_worker.py, uv.lock
This PR adds automodel repo as a submodule and creates DTensorPolicyWorkerV2 to consume parallelize functionality from nemo_automodel apis recently upstreamed.
#578  
```python
```
* ...
=> feat: Create DTensorPolicyWorkerV2 to integrate nemo-automodel apis

uv.lock
This PR removes nvfsdp from uv lock in nemo-rl, consuming an update version of the Automodel submodule.
```python
```
* ...
=> fix: Automodel integration - remove nvfsdp from uv lock.

ray.sub
When running on slurm, hostname resolution sometimes fails - this PR adds a few fallback methods and debugging info to improve robustness
=> chore: ray-sub - improve robustness

nemo_rl/models/policy/__init__.py, nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/dtensor_policy_worker_v2.py, nemo_rl/models/policy/lm_policy.py, nemo_rl/models/policy/megatron_policy_worker.py, pyproject.toml, tests/unit/conftest.py, tests/unit/models/policy/test_dtensor_worker.py, tests/unit/models/policy/test_dtensor_worker_v2.py, tests/unit/models/policy/test_megatron_worker.py, tests/unit/test_config_validation.py, tests/unit/test_recipes_and_test_suites.py
Add a marker called `run_first` to force some tests that fail often first. This includes config and recipe tests.
Also at the same time fix up #863 
Closes https://github.com/NVIDIA-NeMo/RL/issues/863
```python
```
* ...
=> test: introduce "run_first" marker to fail on config changes early

examples/configs/evals/eval.yaml, examples/configs/grpo_math_1B.yaml, examples/configs/grpo_sliding_puzzle.yaml, examples/configs/recipes/llm/grpo-deepscaler-1.5b-24K.yaml, examples/configs/recipes/llm/grpo-deepscaler-1.5b-8K.yaml, examples/configs/recipes/llm/grpo-gemma3-1b-it-1n8g-fsdp2tp1.yaml, examples/configs/recipes/llm/grpo-gemma3-27b-it-16n8g-fsdp2tp8sp-actckpt-long.yaml, examples/configs/recipes/llm/grpo-gspo-deepscaler-1.5b-8K.yaml, examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-1n8g-megatron-fp8.yaml, examples/configs/recipes/llm/grpo-llama3.1-8b-instruct-4n8g-fsdp2tp1-long.v3.yaml, examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-fsdp2tp1.v3.yaml, examples/configs/recipes/llm/grpo-llama3.2-1b-instruct-1n8g-megatron.yaml, examples/configs/recipes/llm/grpo-math-qwen3-30ba3b-megatron-tp4-32k.yaml, examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt-long.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-32b-32n8g-fsdp2tp8sp-actckpt.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4sp.v3.yaml, examples/configs/recipes/llm/grpo-qwen2.5-7b-instruct-4n8g-megatron.yaml, examples/configs/recipes/llm/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1.v3.yaml, examples/configs/recipes/vlm/vlm_grpo-qwen2.5-vl-3b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml, examples/configs/recipes/vlm/vlm_grpo-smolvlm2-2.2b-instruct-clevr-1n2g-dtensor2tp1.v1.yaml, examples/configs/vlm_grpo_3B.yaml, nemo_rl/models/generation/vllm/config.py, nemo_rl/models/generation/vllm/vllm_worker.py, tests/unit/environments/test_code_environment.py, tests/unit/environments/test_retriever.py, tests/unit/experience/test_rollouts.py, tests/unit/models/generation/test_vllm_generation.py, tests/unit/models/generation/test_vllm_large_model.py
This PR add vllm `enable_expert_parallel` to support using EP for generation.
1. As @xxman-google mentioned, this will save memory of MoE models.
2. This is a prerequisite of https://github.com/NVIDIA-NeMo/RL/issues/908 and https://github.com/NVIDIA-NeMo/RL/issues/947.
Currently enable `enable_expert_parallel` won't speedup generation according to tests on DSV3.
1. We can't take the benefit of DP since we didn't use vllm's DP and control it outside now.
2. We use vllm's `naive all2all backend`, haven't support pplx and DeepEP backend.
Will support these in subsequent PRs.
Related https://github.com/NVIDIA-NeMo/RL/issues/908.
=> feat: add vllm enable_expert_parallel

examples/configs/sft_openmathinstruct2_megatron.yaml
Removes the fp8 training args that were erroneously added to the SFT openmathinstruct config. These args are currently unused.
```python
```
* ...
=> fix: remove unused fp8 training args in config

docs/nsys-profiling.md, ray.sub
Fix nsight profiling file sync for multi-node jobs. Previously non-header node files are not synced. 
Closes #1000 
```python
```
* ...
=> feat: Fix nsight profiling file sync for multi-node jobs

nemo_rl/algorithms/grpo.py
Set `flush=True` in GRPO print logging so that ray worker logging (e.g. from VLLM generation workers) is interleaved w/ other logs in the correct order.
```python
```
* ...
=> chore: flush to stdout when print logging during GRPO

nemo_rl/algorithms/grpo.py
Example output after this fix
```
📊 Training Results:
• Loss: 0.1032
• Avg Reward: 0.3486
• Buffer Size: 64
• Avg Trajectory Age: 1.00 steps
⏱️  Timing:
• Total step time: 66.55s
• exposed_generation: 32.52s (48.9%)
• policy_training: 25.05s (37.6%)
• policy_and_reference_logprobs: 4.78s (7.2%)
• buffer_sampling: 1.38s (2.1%)
• logprob_inference_prep: 1.34s (2.0%)
• training_prep: 1.06s (1.6%)
• data_processing: 0.23s (0.4%)
• weight_sync: 0.13s (0.2%)
```
```python
```
* ...
=> fix: Decouple exposed_generation time from weight_sync time

.github/workflows/build-test-publish-wheel.yml
ci: Only run build-test-publish-wheel workflow if env var set
Currently, this check is failing and the fix will require some rework in RL to actually make pip installable viable.
```python
```
* ...
=> ci: Only run build-test-publish-wheel workflow if env var set

ray.sub
Closes: #1019 
Example output:
```
+ echo '[ERROR] Background srun '\''ray-worker-1'\'' died (pid=123456). Could be a failure in startup or an issue with the node preventing the srun to start. Attempting to exit.'
[ERROR] Background srun 'ray-worker-1' died (pid=123456). Could be a failure in startup or an issue with the node preventing the srun to start. Attempting to exit.
+ touch /logdir/5336464-logs/ENDED
+ exit 1
```
=> fix: ray.sub will exit early if any srun fails to launch 

nemo_rl/models/policy/megatron_policy_worker.py
Correctly uses InstantiationMode.STRICT to enable strict loading of megatron bridge configs
Closes https://github.com/NVIDIA-NeMo/RL/issues/1054
```python
```
* ...
=> fix: Correct strict loading megatron bridge config

nemo_rl/models/megatron/community_import.py
This prevents validation errors when loading the checkpoint after the initial import. The problem is that the parallelism settings we use for importing may not pass validation when loading the model for training. For example, if we set EP > 1 and TP > 1, Megatron expects sequence_parallel to be True. sequence_parallel is not needed for importing the model, so we do not set it. In this PR, we fix the issue by resetting the config to the default values (which should not have any validation errors) after loading the model so the defaults get saved to the run_config.yaml.
Closes https://github.com/NVIDIA-NeMo/RL/issues/1060
List issues that this PR closes ([syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-re …
=> fix: Reset parallelism configs to default after initial import

examples/configs/dpo.yaml, examples/configs/recipes/llm/dpo-mistral-nemo-instruct-2407-1n8g-fsdp2tp8-actckpt-long.yaml, nemo_rl/models/policy/__init__.py, nemo_rl/models/policy/dtensor_policy_worker.py, nemo_rl/models/policy/dtensor_policy_worker_v2.py
Help mitigate the performance overheads from clearing cache which is introduced in #926 by making clear cache behaviour optional. 
This PR resolves #1036. 
This PR introduces an additional option for `dtensor_config`. To clear cache between microbatch iterations, add:
```yaml
policy:
dtensor_cfg:
clear_cache_every_n_steps: 1
```
A warning will be displayed before a training iteration indicating that clear cache has been turned on and its potential performance overheads. 
```
(DTensorPolicyWorker[rank=0] pid=3016383) /lustre/fs1/portfolios/coreai/users/yubog/RL/nemo_rl/models/policy/dtensor_policy_worker.py:635: UserWarning: Emptying cache every 1 microbatches
, doing so unnnecessarily would incur a large performance overhead.
(DTensorPolicyWorker[rank=0] pid=3016383) …
```
=> fix: optional clear cache between microbatch iterations

pyproject.toml, uv.lock
This PR adds DeepEP dependencies and won't enable anything by default.
The generation perf w/ DeepEP is still under testing, will have another PR for it.
DeepEP can only work under IBGDA, please make sure the cluster has IBGDA or follow [this guide](https://github.com/vllm-project/vllm/blob/v0.10.2rc1/tools/ep_kernels/configure_system_drivers.sh) to enable it.
We can turn on DeepEP w/ env var `VLLM_ALL2ALL_BACKEND` like below for now, will add param `vllm_cfg.all2all_backend` to replace it in later PR.
```bash
VLLM_ALL2ALL_BACKEND=deepep_high_throughput \
uv run python examples/run_grpo_math.py \
... \
policy.generation.vllm_cfg.enable_expert_parallel=true \
...
VLLM_ALL2ALL_BACKEND=deepep_low_latency \
uv run python examples/run_grpo_math.py \
... \ …
```
=> chore: add DeepEP dependencies

docs/design-docs/logger.md, examples/configs/dpo.yaml, examples/configs/grpo_math_1B.yaml, examples/configs/grpo_math_1B_megatron.yaml, examples/configs/grpo_sliding_puzzle.yaml, examples/configs/rm.yaml, examples/configs/sft.yaml, examples/configs/sft_openmathinstruct2.yaml, examples/configs/vlm_grpo_3B.yaml, nemo_rl/utils/logger.py, pyproject.toml, tests/unit/utils/test_logger.py, uv.lock
Replacement of #716 (just resolving issues in the PR to help it along)
Thanks to @tpoisonooo for driving
=> feat: support swanlab logger

nemo_rl/algorithms/distillation.py, nemo_rl/algorithms/dpo.py, nemo_rl/algorithms/grpo.py, nemo_rl/algorithms/rm.py, nemo_rl/algorithms/sft.py, tests/unit/algorithms/test_distillation.py, tests/unit/algorithms/test_rm.py, tests/unit/algorithms/test_sft.py
PR to replace https://github.com/NVIDIA-NeMo/RL/pull/803
Rebase and apply it to all algorithms
FYI @xxman-google . will make sure to credit the PR to you
=> feat: add valid_tokens_per_sec metric and total_valid_tokens to save state
